// Initial foreground GPS thresholds; meters, seconds and m/s unless otherwise noted.
export const GPS_CONFIG = {
  MAX_ACCEPTABLE_ACCURACY: 25,
  MAX_RUNNING_SPEED: 8,
  MAX_LOCATION_JUMP: 100,
  MIN_LOCATION_DISTANCE: 3,
  MAX_LOCATION_AGE_SECONDS: 15,
  MAX_BACKGROUND_LOCATION_AGE_SECONDS: 300,
  MAX_FUTURE_TIMESTAMP_SECONDS: 5,
  MAX_CONTINUOUS_GAP_SECONDS: 30,
  UPDATE_INTERVAL_MS: 1000,
  UPDATE_DISTANCE_METERS: 1,
  READY_TIMEOUT_MS: 15000,
} as const;

export const BACKGROUND_LOCATION_TASK = 'todaysrunning-location-v1';
